### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by mrgame-memo** [AzuriomCommunity/Plugin-PaysafecardManual#1]
Hi, the plugin seems to only be available in English, how can I change this ?

**Comment by Javdu10** [comment]
I did not take the time to do translation but it's rather simple.

You need to create a directory for a language, For example "fr" then your translation files

Then you would need to replace all hardcoded text to something like 

`{{ trans('paysafecardmanual::messages.fields.name') }}`

https://laravel.com/docs/7.x/localization#introduction

**Comment by MrMicky-FR** [comment]
The french translation was added in 817af63770ba7b586a2789714dbdf20c4b2757b8
